[tool.black]
line-length = 100
target-version = ['py310']

[tool.ruff]
line-length = 100
target-version = "py310"
extend-select = ["B", "C4", "I", "N", "UP", "ANN"]
ignore = ["ANN101", "ANN102", "ANN401"]
exclude = ["venv", "__pycache__", "node_modules", "dist"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
strict_optional = true


